<?php

/**
 * @file
 * Contains d8_json_migrate.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function d8_json_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the d8_json_migrate module.
    case 'help.page.d8_json_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal8 migrate json example') . '</p>';
      return $output;

    default:
  }
}
